<%@ Page Title="" Language="C#" MasterPageFile="~/Base.Master" AutoEventWireup="true" CodeBehind="cProfesores.aspx.cs" Inherits="ColegioParcial.UI.Consultas.cProfesores" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <br />
    <br />
    <div class=" container page-header col-xs-12 col-sm-4 d-inline-block">
        <h1>Consulta de Profesores</h1>
    </div>

    <br />
    <br />

    <div class="col-xs-12 col-sm-4 d-inline-block">
        <asp:DropDownList CssClass="form-control" ID="FiltrarDropDownList" runat="server">
            <asp:ListItem>Todos</asp:ListItem>
            <asp:ListItem>ID</asp:ListItem>
            <asp:ListItem>Nombre</asp:ListItem>
            <asp:ListItem>Fecha Ingreso</asp:ListItem>
            
        </asp:DropDownList>
    </div>

    <div class="col-xs-12 col-sm-7 d-inline-block">
        <div class="form-group">
            <asp:TextBox CssClass="form-control col-7" ID="FiltrarTextBox" runat="server" autocomplete="off"></asp:TextBox>
        </div>
    </div>

    <div class="col">
        <div class="form-group">
            <asp:CheckBox ID="FiltrarFechaCheckBox" runat="server" />
            <label for="ContentPlaceHolder1_FiltrarFechaCheckBox">Fitrar por fecha</label>
        </div>
    </div>

    <asp:Panel ID="FechasPanel" runat="server">
        <div class="col-xs-12 col-sm-4 d-inline-block">
            <div class="form-group">
                <label for="ContentPlaceHolder1_FechaDesdeTextBox">Desde</label>
                <asp:TextBox type="date" CssClass="form-control" ID="FechaDesdeTextBox" runat="server" autocomplete="off"></asp:TextBox>
            </div>
        </div>

        <div class="col-xs-12 col-sm-7 d-inline-block">
            <div class="form-group">
                <label for="ContentPlaceHolder1_FechaHastaTextBox">Hasta</label>
                <asp:TextBox type="date" CssClass="form-control col-7" ID="FechaHastaTextBox" runat="server" autocomplete="off"></asp:TextBox>
            </div>
        </div>
    </asp:Panel>

    <div class="float-left container">
        <asp:Button CssClass="btn btn-primary  d-flex justify-content-around " ID="BuscarButton" runat="server" Text="Buscar" OnClick="BuscarButton_Click" />
    </div>


    <br />
    <br />
    <br />


    <div class="row container">
        <div class="col-10">
            <asp:GridView CssClass="table" BorderStyle="None" AutoGenerateColumns="False" GridLines="Horizontal"
                ID="ProfesoresConsulta" DataKeyNames="ProfesorId,Nombre" ShowFooter="True" runat="server" EnableModelValidation="False" AutoGenerateEditButton="True" AutoGenerateDeleteButton="True" OnRowDeleting="ProfesoresConsulta_RowDeleting" OnRowEditing="ProfesoresConsulta_RowEditing" OnRowUpdating="ProfesoresConsulta_RowUpdating" OnSelectedIndexChanged="ProfesoresConsulta_SelectedIndexChanged1">
                <HeaderStyle CssClass="thead-inverse table-bordered" />
                <Columns>
                    <asp:TemplateField HeaderText="ID">
                        <ItemTemplate>
                            <asp:Label ID="ProfesorId" runat="server" Text='<%# Bind("ProfesorId") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>

                    <asp:BoundField DataField="Nombre" HeaderText="Nombres" />

                    <asp:BoundField DataField="Apellido" HeaderText="Apellido" />

                    <asp:BoundField DataField="Tanda" HeaderText="Tanda" />

                </Columns>
                <FooterStyle CssClass="bg-light" />
            </asp:GridView>

        </div>
    </div>
</asp:Content>
